# Generated by Django 4.0.6 on 2022-07-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='decc',
            new_name='desc',
        ),
    ]
